# Basic
title: Mageric
subtitle: 42 世界尽头
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Mageric的个人小站.
creator: <a href="http://mageric-one.com">@mageric</a>

#url: "http://vno.onevcat.com"
baseurl: ""
safe: false
#pygments: true

permalink: /:year/:month/:title/

# Format
highlighter: rouge

markdown: kramdown
kramdowm:
  input : GFM
  hard_wrap: false

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: OldSite, description: My old site, url: 'http://mageric-one.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: magericyoung
    github: Mageric0412
    instagram: mageric0412
    website: mageric-one.com
    mail: mageric0412@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
